### ISSUE TITLE
tgadderbot.py issue

### ISSUE THREAD

**Issue by Soyeb78692** [sazzadrahel/TelegramScraperBot#1]
I am getting this error while using tgadderbot.py 

How can I fix this ?
 
 
 /_  __/__  / /__  ____ __________ _____ ___
  / / / _ \/ / _ \/ __ `/ ___/ __ `/ __ `__ \
 / / /  __/ /  __/ /_/ / /  / /_/ / / / / / /
/_/  \___/_/\___/\__, /_/   \__,_/_/ /_/ /_/
                /____/

   Version: 1.1 | Author: Rahel

(i) Creating sessions for all accounts...
Traceback (most recent call last):
  File "C:\Users\user\Documents\Telegram\New folder\TelegramScraperBot-main\tgadderbot.py", line 89, in <module>
    clnt.send_code_request(phn)
  File "C:\Users\user\anaconda3\lib\site-packages\telethon\sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "C:\Users\user\anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\user\anaconda3\lib\site-packages\telethon\client\auth.py", line 514, in send_code_request
    result = await self(functions.auth.SendCodeRequest(
  File "C:\Users\user\anaconda3\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Users\user\anaconda3\lib\site-packages\telethon\client\users.py", line 84, in _call
    result = await future
telethon.errors.rpcerrorlist.ApiIdInvalidError: The api_id/api_hash combination is invalid (caused by SendCodeRequest)

C:\Users\user\Documents\Telegram\New folder\TelegramScraperBot-main>
C:\Users\user\Documents\Telegram\New folder\TelegramScraperBot-main>
C:\Users\user\Documents\Telegram\New folder\TelegramScraperBot-main>

**Comment by webexpertinbd** [comment]
Code updated,, Download and try again. Maybe the issue has been solved
